import type { Metadata } from "next";
import { StackProvider, StackTheme } from "@stackframe/stack";
import { stackClientApp } from "../stack/client";
import { Inter, Roboto_Mono } from "next/font/google";
import { CryptoPolyfill } from "./crypto-polyfill";
import CyberpunkParticles from "@/components/CyberpunkParticles";
import "./globals.css";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${robotoMono.variable} cyberpunk-bg antialiased`}
      ><CryptoPolyfill /><CyberpunkParticles /><StackProvider app={stackClientApp}><StackTheme>
        <div className="app-shell">{children}</div>
      </StackTheme></StackProvider></body>
    </html>
  );
}
